### PR TITLE
adds in jvm option support for cli command calls

### PR DESCRIPTION
**Pull request by antoniobeyah**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @antoniobeyah

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by antoniobeyah** [comment]
this partially addresses #441

**Comment by antoniobeyah** [comment]
@schisamo @tfitch @yzl @tas50 @mtyler (maintainers) it looks like the new version of rubocop is failing my build, please fix master.  It looks like there are already some PRs out there that address this and this project has become a bit inactive (last commit november 21, 2015).  Can you let me know how I can become a maintainer?  I spend a fair amount of time with this cookbook and have lots of monkey-patches changing the behavior that I would like to get in core.

Thanks,
Antonio

**Comment by antoniobeyah** [comment]
@schisamo @tfitch @yzl @tas50 @mtyler daytime bump

**Pull request merged**
