### PR TITLE
Fix #570: JNLP Windows slaves broken

### LINKED ISSUE #570: Windows JNLP slave failing with error
### Cookbook version
jenkins 4.2.1

### Chef-client version
12.10.24

### Platform Details
Windows Server 2012R2

### Scenario:
When creating a new JNLP slave, an Chef::Exceptions::EnclosingDirectoryDoesNotExist is raised
 
### Steps to Reproduce:
Just put a resource like this in your cookbook:
```ruby
jenkins_windows_slave node['hostname'].downcase do
  remote_fs 'D:\Bld'
  user 'azure'
  password 'P2ssw0rd'
  executors 1
  usage_mode 'exclusive'
end
```

### Expected Result:
A new slave running and registered with the master

### Actual Result:
```
================================================================================
Error executing action `create` on resource 'jenkins_windows_slave[vm]'
================================================================================

Chef::Exceptions::EnclosingDirectoryDoesNotExist
------------------------------------------------
remote_file[d:\Bld/jenkins-slave.exe] (dynamically defined) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory d:\Bld does not exist.
```

### PR DESCRIPTION
**Pull request by emmanuelguerin**
### Issues Resolved

#570 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by iennae** [comment]
@emmanuelguerin Appreciate that you are having a problem with the current cookbook. This is not the right way to solve the problem. We are in the process of cleaning up this cookbook but it will take some time. I'm going to close this PR and leave your issue open. We are aware of the problem you've reported.

**Comment by emmanuelguerin** [comment]
@iennae ​My intent was to offer a quick patch to restore functionality without reorganizing the code, as I realized from the history that you were in that process of refactoring.
As is, the windows_slave resource is not usable without gettting what is in slave_jnlp in the calling recipe.
Sorry I couldn't help.

**Comment by jblaine** [comment]
@iennae could you clarify "not the right way to solve the problem"? Is that referring to the code submitted, or that emmanuel was wrong to even submit a PR?

**Comment by iennae** [comment]
@jblaine it's never wrong to submit a PR. I appreciate folks trying to solve problems. It's about the specific strategy to solve the problem of the broken JNLP windows slave recipe. Currently the cookbook as implemented has the wrong abstraction around implementation of jnlp and ssh which leads to overlap and implementation challenges. Solving the reported problem is on our todo list for next week. Thanks.

**Comment by rneu31** [comment]
Did "next week" ever come?

**Pull request closed without merging**
