### PR TITLE
Support ECDSA private keys in addition to RSA keys.

### PR DESCRIPTION
**Pull request by don-code**
### Description

The cookbook currently supports only RSA private keys when importing private key credentials into Jenkins. This PR allows the use of ECDSA private keys in addition to RSA private keys.

Care has been taken to ensure that the cookbook behaves in a backwards-compatible manner should it be presented unexpected input - specifically, it will fall back to the assumption of an RSA key even if an RSA key is not specified.

### Issues Resolved

None

### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @don-code

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by don-code** [comment]
Regarding the checklist:

1. Integration tests pass against the last non-2.x Jenkins LTS (1.651.3). As said tests don't pass off a clean master otherwise, this seems out of scope for this PR.
1. I don't consider this documentation-worthy for the README, as it's not explicitly called out that only RSA keys are suppored by the cookbook despite ECDSA keys being supported within Jenkins.

**Comment by tas50** [comment]
Thanks for adding this

**Pull request merged**
