### PR TITLE
jenkins_view HWRP

### PR DESCRIPTION
**Pull request by danfruehauf**
Supports `jenkins_view`. Quite a bit of code duplication with `jenkins_job` HWRP, however if this has a chance of getting merged I will refactor it and eliminate the duplication + add proper tests.

### CODE REVIEW

**Comment by schisamo** [comment]
@danfruehauf So I think we can accomplish this using the Groovy API without requiring the XML. We here at Chef Software create views on the fly in a Chef resource that manages our pipelines. Here is the helper function in this resource:

```ruby
#
# Adds the Jenkins job represented by `job_name` to the generated pipeline
# for.
#
def add_jenkins_job_to_view(view_name, job_name)
  # Creates a pipeline specific view and adds the current job
  add_job_to_view = Chef::Resource::JenkinsScript.new("add-#{job_name}-to-view", run_context)
  add_job_to_view.command(
    <<-GROOVY.flush
      import hudson.model.*
      import jenkins.model.*
      view_name = '#{view_name}'
      job_name = '#{job_name}'
      jenkins = Jenkins.instance
      pipeline_view = jenkins.getView(view_name)
      // Create the project-specific view if it doesn't exist
      if (!pipeline_view) {
        pipeline_view = new ListView(view_name)
        jenkins.addView(pipeline_view)
      }
      job = jenkins.getItem(job_name)
      // Add the job to the view
      if (!pipeline_view.contains(job)) {
        pipeline_view.add(job)
      }
    GROOVY
  )
  add_job_to_view.run_action(:execute)
end
```

I think you can take the rough idea here and turn it into a nice resource. The provider code should break apart this Groovy and make a call in `load_current_resource` to attempt to load a current view. You then would have more groovy in the `:create` and `:delete` actions.

**Comment by danfruehauf** [comment]
@schisamo I think I understand what you mean. This will just slightly reduce the amount of code required. BTW, I can argue about doing the same for `jenkins_job` then.

I think further down the track it would be nice to factor this resource provider so it takes parameters rather than a XML blob. But that's not very simple as there are a fair few plugins that implement views (pipelines for instance). Modelling all of them can be tricky and can get out of date quick.

Either way, I'll modify this to use groovy code rather than `create-view` and `get-view`.

**Comment by danfruehauf** [comment]
And... about modelling the views not with XML. I'm after a bit more than having a list view with a few views in it. I'm actually after a pipeline view and I'd like to tweak a few options there. Might require quite a bit of groovy code...

**Comment by danfruehauf** [comment]
@schisamo So here it is, this enables us to generate simple views and define jobs. It's idempotent and uses only groovy. It also uses groovy to probe the current defined jobs in a view and a JSON exchange format.

Still using `delete-job` when deleting as it saves a lot of code.

The next step for me is to allow groovy code execution so more sophisticated views can be handled, such as `BuildPipelineView`. This will mostly require overriding `create_view` and `configure_view` closures.

**Comment by danfruehauf** [comment]
The second commit will allow passing a groovy snippet to create and configure the view.

In my case I need to use `BuildPipelineView` extensively. So my recipe looks something like:
```
pipeline_code = <<-GROOVY
import au.com.centrumsystems.hudson.plugin.buildpipeline.*

def buildViewTitle = '#{pipeline_name}'
def cssUrl = ""
def triggerOnlyLatestJob = false
def alwaysAllowManualTrigger = true
def showPipelineParameters = true
def showPipelineParametersInHeaders = true
def startsWithParameters = false
def refreshFrequency = 3
def showPipelineDefinitionHeader = true
def noOfDisplayedBuilds = "#{pipeline_databag['displayed_builds'] || 10}"
def gridBuilder = new DownstreamProjectGridBuilder('#{first_job}')

create_view = { name ->
  return new BuildPipelineView(
    view_name,
    buildViewTitle,
    gridBuilder,
    noOfDisplayedBuilds,
    triggerOnlyLatestJob,
    cssUrl
  )
}
configure_view = { view ->
  view.setGridBuilder(gridBuilder)
  view.setBuildViewTitle(buildViewTitle)
  view.setCssUrl(cssUrl)
  view.setNoOfDisplayedBuilds(noOfDisplayedBuilds)
  view.setTriggerOnlyLatestJob(triggerOnlyLatestJob)
  view.setAlwaysAllowManualTrigger(alwaysAllowManualTrigger)
  view.setShowPipelineParameters(showPipelineParameters)
  view.setShowPipelineParametersInHeaders(showPipelineParametersInHeaders)
  view.setShowPipelineDefinitionHeader(showPipelineDefinitionHeader)
}
GROOVY

jenkins_view pipeline_name do
  code pipeline_code
end
```

So this interface altogether support the basic Jenkins views, but also caters for people who would like to extend it using plugins (like me). In that case - they'll have to write the groovy code to do the heavy lifting. They might prefer using a simple XML template, but as you stated @schisamo, you much prefer a groovy DSL to define the views rather than a templated XML - so here we go.

**Comment by daspilker** [comment]
Have a look at the [Job DSL plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin) for Jenkins. It allows to define views and jobs in a convenient DSL.

You need the create a "seed" job which will then create/update/delete views and jobs defined in the DSL. You can use the existing Jenkins cookbook to create the seed job.

There is a short [presentation](https://www.cloudbees.com/event/topic/lightning-talk-2-configuration-code-job-dsl-plugin) which gives a good introduction. And the docs are available on [GitHub](https://github.com/jenkinsci/job-dsl-plugin/wiki).

The Jenkins cookbook does not need to duplicate all Job DSL features and invent a new DSL.

**Comment by danfruehauf** [comment]
@daspilker Very nice plugin, thanks for bringing it up. I might use it on my own jenkins installation.

However for this cookbook I see a bit of an issue -  the cookbook will then **have** to rely on the job dsl plugin - and that's not up to me to decide.

**Pull request merged**
