### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by cheeseplus**
Signed-off-by: Seth Thomas <sthomas@chef.io>

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by ehaselwanter** [comment]
is there any 'breaking' change? the jump to 5.x is irritating me if I look at the changelog

**Comment by ehaselwanter** [comment]
anyways. I really appreciate seeing progress in with the cookbook :-)

**Comment by StephenKing** [comment]
maybe jenkins 2 support? I'm also very thankful!

**Comment by cheeseplus** [comment]
@ehaselwanter there are definitely a few things that would be considered breaking

- stable is now default for grabbing builds and update-center
- jvm_options are set for 2.x by default
- since it's 2.x you'll want to check out the test recipe for the plugins needed that were moved out of core

I'll review and make some notes since I can call this out better like I've done for some other recent major rewrites. Most of the changes were in the service of 2.x support or fixing things that were inherently broken (bad urls, dpkg_autostart).

**Pull request merged**
