### PR TITLE
Increase test coverage

### PR DESCRIPTION
**Pull request by josh-barker**
### Description

This is to increase the test coverage for the cookbook.

### Issues Resolved

* Increase SV timeout to `30` seconds in kitchen file (https://github.com/chef-cookbooks/jenkins/pull/692/commits/1f3f817ec17f869a717f3cc0ada88f7d4e6a97bf)
* Fix bug where cannot find version of plugin from plugin universe (https://github.com/chef-cookbooks/jenkins/pull/692/commits/f3c45dea00d443ffa261d0dc97c1f4e7244e38c1)
* Fix `delete` action on jnlp slave (https://github.com/chef-cookbooks/jenkins/pull/692/commits/a00572c305c985578bfbe07875e0dd055cbc9400)
* Convert custom Jenkins `ServerSpec` resources to `InSpec` resources
* Convert `ServerSpec` tests to `InSpec` tests
* Reduce number of suites and moved as many tests into the smoke suites
 

### To Do:
- [ ]  Cleanup ServerSpec tests and resources

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by josh-barker** [comment]
This is a WIP. Need Travis to run tests.

**Comment by josh-barker** [comment]
Hey @tas50 

This PR is almost finished; I just need to 
- delete all the ServerSpec tests and helpers
- update kitchen.yml to remove all the redundant suites

Can you review before I do the final cleanup, or did you want me to delete all the ServerSpec files first?

I'm not fussed either way, but it could be easier to compare the ServerSpec tests vs the InSpec tests file to file, rather than `git diff`, as there's going to be a lots of files deleted.

For example, comparing `test/integration/jenkins_job_*/*` with `test/integration/jenkins_smoke/controls/jenkins_job.rb`

**Comment by tas50** [comment]
This is massive and seems all legit. Thank you so much for taking the time to put it all together. Nothing stands out to me so feel free to keep on the good work and I can merge this whenever you want. I added you as a collaborator on the cookbook since at this point you know ore about the setup of things than I do.

**Comment by josh-barker** [comment]
No worries. :) 
I'll keep cleaning it up & will let you know when its ready

**Comment by tas50** [comment]
@josh-barker any reason not to merge what you have here and then do any further cleanup in another PR. It would be great to get this on master.

**Comment by josh-barker** [comment]
Hey @tas50, sounds good. Let's get this into master. :-)

**Pull request merged**
