### PR TITLE
SSH retry with integration tests

### PR DESCRIPTION
**Pull request by jsmickey**

### CODE REVIEW

**Comment by jsmickey** [comment]
@schisamo Thanks for your patience.  This PR has a single commit and passing integration tests.

**Comment by 3dinfluence** [comment]
Just wanted to say that this patch is working for us in production.  Thanks @jsmickey.

**Comment by iennae** [comment]
Thanks for the contribution @jsmickey. We are going to try to work this in to the cookbook by the end of the month.

**Comment by bhipple** [comment]
Fantastic, I was just looking for this feature!

**Comment by iennae** [comment]
I've rebased and merged this with #532. There may be some minor issues with the PR, but rather than delaying on merging and having to rebase again when I'm resolving some other issues with this cookbook, I want to get a release of this out in the next few days that includes this patch since folks have reported it working for them.

**Pull request closed without merging**
