### PR TITLE
Fix #670: Support old slave_jar_resource function still in use in windows slave…

### LINKED ISSUE #670: JenkinsWindowsSlave fails due to slave_jar_resource no longer defined in JenkinsJnlpSlave
### Cookbook version
5.0.5

### Chef-client version
12.0.3

### Platform Details
windows 6.3.9600

### Scenario:
create windows jenkins slave

### Steps to Reproduce:
define a windows slave like so:
if platform_family?('windows')
    jenkins_home = "C:/jenkins_#{windows_user}"
    jenkins_user = "#{windows_domain}\\#{windows_user}"
    directory jenkins_home do
        owner jenkins_user
    end
    jenkins_windows_slave node.name do
        remote_fs       jenkins_home
        user            jenkins_user
        password        windows_password
        description     'Configured by chef'
        executors       1
        usage_mode      'exclusive'
        labels          options['labels_common'] + options['labels_more'] + automatic_labels
    end
end

### Expected Result:
jnlp windows slave created

### Actual Result:
chef run fails with exception:
 NameError
 ---------
 No resource, method, or local variable named `slave_jar_resource' for `Chef::Provider::JenkinsWindowsSlave ""'

### PR DESCRIPTION
**Pull request by timor-raiman**
… provider

### Description

Fix #670: Support old slave_jar_resource function still in use in windows slave

### Issues Resolved

#670 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by skylerto** [comment]
@timor-raiman can you fix the CI issues and push back up?

```
libraries/slave_windows.rb:104:5: C: Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
        return @slave_jar_resource if @slave_jar_resource
    ^^^^
libraries/slave.rb:154:60: C: Layout/SpaceBeforeBlockBraces: Space missing to the left of {.
      new_resource.labels |= current_resource.labels.select{ |i| i[/^prsrv_/] }
```

**Comment by skylerto** [comment]
@tas50 any chance this could be merged in with the CI fixes?

**Comment by tas50** [comment]
This will need to be DCO signed off before we can merge it.

**Comment by tas50** [comment]
Closing in favor of #672

**Pull request closed without merging**
