### PR TITLE
Changes endpoint for 'wait_until_ready'

### PR DESCRIPTION
**Pull request by optiminimal**
This allows the ready check (to see if Jenkins is ready after a restart)
to work even if "HTTP Header by reverse proxy" Security Realm is enabled
(which expects a "Header User Name" to be set) by polling an
"Unprotected URL" (built-in URLs that are excluded from authentication)

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by optiminimal** [comment]
@schisamo @smurawski 
I just got added to the Schuberg Philis contributors list
https://supermarket.chef.io/ccla-signatures/68/contributors

but the bot does not seem to pick this up. Can either of you guys help me out?

**Comment by iennae** [comment]
@optiminimal I know it's been a while since you submitted this change, but can you point me to a place where I can find more information about this proposed change? Thanks!

**Comment by optiminimal** [comment]
Hi @iennae 
Thanks for getting back :)

There is currently no open issue for this proposed change and it only affects jenkins instances using the 'reverse-proxy-auth-plugin'.

The 'wait_until_ready' check returns a 500 Server Error when accessing the index page in this case. (breaking the chef run after the timeout as the cookbook assumes jenkins not be ready to accept more commands)

My change verifies that the jenkins instance is up and running by checking the status code of an unprotected page (in this case /whoAmI).

I could see two places for this fix. Either here as per my commit, or in the ''reverse-proxy-auth-plugin', by changing it to not throw a 500 for unauthenticated users accessing the index page.

I feel that making this change in the jenkins cookbook is a more structural fix though.


What are you thoughts on this, also please advise if I should open an issue for this proposed change first (to encourage a discussion around this functionality).

**Pull request closed without merging**
