### PR TITLE
slave_jnlp: fixed the undefined method errors

### LINKED ISSUE #531: jenkins_jnlp_slave fails with undefined method
### Cookbook version

4.0.1
### Chef-client version

12.15.19
### Platform Details

Centos 7, 3.10.0-327.28.3.el7.x86_64
### Scenario:

Trying to install a Jenkins JNLP slave.
### Steps to Reproduce:

```
jenkins_jnlp_slave ipaddress do
  remote_fs '/home/jenkins'
  action [:create, :connect]
  not_if { master == 'localhost' }
end
```
### Expected Result:

The Jenkins JNLP slave is set up.
### Actual Result:

```

           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.251]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `slave_jar_url' for Chef::Resource::RemoteFile

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb

            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'

           jenkins_jnlp_slave("192.168.211.251") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.251"
             usage_mode "normal"
             description "Jenkins slave 192.168.211.251"
             group "jenkins"
             user "jenkins"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux

       Recipe: chef-client::systemd_service
         * service[chef-client] action restart
           - restart service service[chef-client]
       Recipe: misc::hosts_entry
         * service[network] action restart
           - restart service service[network]

       Running handlers:
       [2016-10-19T17:14:49+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-10-19T17:14:49+02:00] ERROR: Exception handlers complete
       Chef Client failed. 57 resources updated in 43 seconds
       [2016-10-19T17:14:49+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-10-19T17:14:49+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-10-19T17:14:49+02:00] ERROR: jenkins_jnlp_slave[192.168.211.251] (mnet_jenkins::slave line 70) had an error: NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       [2016-10-19T17:14:50+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Here's the stack.out:

```
-----> Execute command on jenkins-slave-centos07.
       Generated at 2016-10-19 17:14:49 +0200
       NoMethodError: jenkins_jnlp_slave[192.168.211.251] (mnet_jenkins::slave line 70) had an error: NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:1347:in `method_missing'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `build'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/dsl/declare_resource.rb:285:in `build_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'
       (eval):2:in `block in action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `compile_and_converge_action'
       (eval):2:in `action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:145:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:603:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:69:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:96:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:669:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:703:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:54:in `load'
       /opt/chef/bin/chef-client:54:in `<main>'

       >>>> Caused by NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:1347:in `method_missing'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `build'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/dsl/declare_resource.rb:285:in `build_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'
       (eval):2:in `block in action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `compile_and_converge_action'
       (eval):2:in `action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:145:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:603:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:69:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:96:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:669:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:703:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:54:in `load'
```

### PR DESCRIPTION
**Pull request by docwhat**
It's ugly, but it works.

Fixes #531

### CODE REVIEW

**Comment by iennae** [comment]
I think #536 resolved the issue. Can you verify? Thanks.

**Comment by iennae** [comment]
Based on the comments left in #531 it looks like the java attributes that you've added are needed. We need to do that in a slightly cleaner way so I'll have to look at this in more detail later. Thanks.

**Comment by docwhat** [comment]
Yeah, this is what remains.

**Comment by docwhat** [comment]
FYI: I've been using this for the past 6 days with no issues.  So it at least gets the dang JNLP stuff working again.

**Comment by lamont-granquist** [comment]
if you leave off the `the_` prefix on the local variables does rubocop get annoyed?   if not, i think those are unnecessary and when i see `thing = thing` i know its a scope issue that is being worked around.

**Comment by iennae** [comment]
@docwhat To clarify my later, I'm going to look at this later today. Thanks.

**Comment by docwhat** [comment]
@lamont-granquist:

> if you leave off the the_ prefix on the local variables does rubocop get annoyed? if not, i think those are unnecessary and when i see thing = thing i know its a scope issue that is being worked around.

If you want it changed, I'll change it.

I didn't know rubocop was being used because there were a bunch of errors when running it anyway; so I assumed it wasn't being used.

The `the_` prefix doesn't seem to annoy rubocop.

Since I can't use the same name as the method `e.g. java = java` I opted to prefix them in a common way so they are easy to identify and I didn't have to come up with a more meaningful name (which if it existed should be the name of the method we're saving the value of anyway).

I've run across this problem before when using blocks for resources and I don't have a pattern for dealing with it that looks good, is easy to understand, and works. :-/  It'd be nice if there was a general pattern for this...

I played with doing `this = self` and using `java: this.java` or something like that but its still ugly.

**Comment by lamont-granquist** [comment]
hmmmm, `java = java`  compiles in my head and creates a local var that shadows the method, if it doesn't work in practice though then carry on...

**Comment by docwhat** [comment]
> hmmmm, java = java compiles in my head and creates a local var that shadows the method, if it doesn't work in practice though then carry on...

Huh... its works in ruby 2.3.1 but in 2.2.5 it returns `nil`. I would never have thought to try it because it just looks... wrong.

``` .rb
class Foo
  def bar
    'bar'
  end

  def baz
    bar = bar
    p bar
  end

  def baz2
    bar = self.bar
    p bar
  end
end

f = Foo.new

f.baz
# => 'bar' in ruby 2.3.1
# => nil in ruby 2.2.5

f.baz2
# => 'bar'
```

I can switch it to the `self.bar` syntax if you prefer it (and fix the previous `slave_jar_remote_url = slave_jar_url` to use the same syntax.

**Comment by lamont-granquist** [comment]
how about just doing this?

```ruby
          r = build_resource(:runit_service, new_resource.service_name) do
            cookbook('jenkins')
            run_template_name('jenkins-slave')
            log_template_name('jenkins-slave')
          end
          # we need to do this because of scoping
          r.options(
              new_resource: new_resource,
              java_bin:    java,
              slave_jar:   slave_jar,
              jnlp_url:    jnlp_url,
              jnlp_secret: jnlp_secret
            )
        end
```

**Comment by docwhat** [comment]
So switching to `java = self.java` doesn't work for some reason. Not entirely sure why. :-/

@lamont-granquist's code would have to look like this:

``` .rb
    def service_resource
      @service_resource ||=
        begin
          # Ensure runit is installed on the slave.
          include_recipe 'runit'

          r = build_resource(:runit_service, new_resource.service_name) do
            cookbook('jenkins')
            run_template_name('jenkins-slave')
            log_template_name('jenkins-slave')
          end
          # we need to do this because of scoping
          r.options(
              new_resource: new_resource,
              java_bin:    java,
              slave_jar:   slave_jar,
              jnlp_url:    jnlp_url,
              jnlp_secret: jnlp_secret
            )
          r
        end
    end
```

Or I could use `.tap` instead of the trailing `r` at the end.

Thoughts, @iennae?

**Comment by docwhat** [comment]
Alternatively, I could use `scoped_` instead of `the_` in the variable names in my original approach.

Or maybe:

``` .rb
    def service_resource
      @service_resource ||=
        begin
          # Ensure runit is installed on the slave.
          include_recipe 'runit'

          build_resource(:runit_service, new_resource.service_name).tap do |r|
            # We need to use .tap() to access methods in the provider's scope.
            r.cookbook('jenkins')
            r.run_template_name('jenkins-slave')
            r.log_template_name('jenkins-slave')
            r.options(
              new_resource: new_resource,
              java_bin:    java,
              slave_jar:   slave_jar,
              jnlp_url:    jnlp_url,
              jnlp_secret: jnlp_secret
            )
          end
        end
    end
```

**Comment by lamont-granquist** [comment]
i'm not wild about `tap` i always stumble mentally when i see it, dunno why...    and are you certain that still works because it's still inside the block and still being instance_eval'd against the built RunitService resource object?

**Comment by docwhat** [comment]
I'm running it now on about 30+ hosts... so it does work.

I'm torn on `.tap()` myself.

If you want to get more used to it, try to re-implement it yourself.  It helped me get a better idea of what it is.

However, requiring all developers to do that isn't a good UX. :-/

I'll push up the change...gimme a second.

**Comment by lamont-granquist** [comment]
oic with `tap` you're inside a block being passed to `tap`, not inside a block being passed to `build_resource` so it works...

coffee must have kicked in a bit...

**Comment by docwhat** [comment]
So that's thumbs up on the change?

**Comment by docwhat** [comment]
W00T!

**Comment by iennae** [comment]
Thanks for your perseverance. We appreciate your contributions :)

**Comment by docwhat** [comment]
Thanks for fixing it!  BTW: It's been working all day without problems. :-)

**Pull request merged**
