### PR TITLE
Use fully qualified master recipe name

### PR DESCRIPTION
**Pull request by stefhen**
The shortname for the master recipe in metadata.rb is not fully qualified and this breaks the cookbook on the RightScale platform.

This PR simply updates metadata to use the full ```jenkins::master``` recipe name.

### CODE REVIEW

**Comment by mtyler** [comment]
:+1:

**Comment by yzl** [comment]
:+1:

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @stefhen

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by stefhen** [comment]
Could this be merged so that we may reference this cookbook directly vs. having to fork it? Thanks!

**Comment by schisamo** [comment]
@stefhen It looks like your branch needs to be rebased on master.

**Comment by stefhen** [comment]
Hi @schisamo I believe I've rebased this properly. If this isn't correct I can close this PR and just create a new one based on the current state of ```master``` and resubmit.


Thanks!

**Pull request merged**
