### PR TITLE
Add extra variables as attributes

### PR DESCRIPTION
**Pull request by rnt**
### Description

This PR allow to users to set extra environment variables to init scripts.
For example, setting configuration-as-code plugin I need to set `CASC_JENKINS_CONFIG` variable on sysconfig file (RHEL/CentOS using package).

### Issues Resolved

None.

### CODE REVIEW

**Comment by acrewdson** [comment]
I recently ran into this same situation with respect to JCasC (as mentioned above by @rnt). I imagine this will become a more frequent problem for people as JCasC is more widely adopted: initial provisioning of Jenkins with this cookbook, then further configuration with JCasC. The changes in this PR will be important to have.

**Comment by acrewdson** [comment]
Just expressing support again for merging this PR, it'd be a huge help. /cc @tas50 

Thanks!

**Comment by acrewdson** [comment]
Checking again on whether this might be merge-able. Let me know if there's anything I can do to help make that happen. Thank you!

**Comment by tas50** [comment]
Thanks @rnt

**Pull request merged**
