### PR TITLE
Add possibility to set Jenkins slave process group from attribute

### PR DESCRIPTION
**Pull request by TheSAS**
### Description

Add possibility to set Jenkins slave process group from node['jenkins']['slave']['runit']['groups'] array.

### Issues Resolved

If jenkins user are added to different groups (apache and docker in example), output of a shell execute commands `groups` and `groups jenkins` will be different.
```
12:44:30 + groups
12:44:30 jenkins
12:44:30 + groups jenkins
12:44:30 jenkins : jenkins apache docker
```

Root cause is a chpst `-u` option.
> -u [:]user[:group]
>  setuidgid.  Set uid and gid to the user's uid and gid, as found in /etc/passwd.  If user is followed by a colon and a group, set the gid to group's gid, as found in  /etc/group, instead of user's gid.  If group consists of a colon-separated list of group names, chpst sets the group ids of all listed groups.  If user is  prefixed  with a colon, the user and all group arguments are interpreted as uid and gids respectivly, and not looked up in the password or group file.  **All initial supplementary groups are removed.**

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by sean-abbott** [comment]
+1, please.

**Comment by cdoughty-r7** [comment]
This has an associated issue as well: https://github.com/chef-cookbooks/jenkins/issues/685

**Comment by aaronm-cloudtek** [comment]
Any plans to get this merged? Running into the same issue

**Comment by aaronm-cloudtek** [comment]
I'm wondering if the lack of tests is what is preventing this from getting merged? Would it help if I wrote some?

**Comment by josh-barker** [comment]
Hey @aaronm-cloudtek and @TheSAS there are merge conflicts for some files.

More tests would be good too.

**Comment by TheSAS** [comment]
Closed, as https://github.com/chef-cookbooks/jenkins/issues/685 get released.

**Pull request closed without merging**
