### PR TITLE
Add blazemeter and sauce credentials resources

### PR DESCRIPTION
**Pull request by llibicpep**
### Description

This PR adding `jenkins_sauce_ondemand_credentials` and `jenkins_blazemeter_credentials` resources

### Issues Resolved

https://github.com/chef-cookbooks/jenkins/issues/546

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

Obvious fix.

### CODE REVIEW

**Comment by llibicpep** [comment]
Hi guys, having hard times trying to actually run tests - failing with various issues. I assuming this is because Jenkins 2.0 does not yet supported? Though I have failures on 1.580.1 as well. Anyone can assist?

**Comment by StephenKing** [comment]
I'm not sure if it makes sense to add so plugin-specific additions.. This makes the scope of this cookbook very very broad.

**Comment by llibicpep** [comment]
Makes sense. Assuming suggestion would be having separate cookbooks that dependant on this one and brings desired functionality?

**Comment by StephenKing** [comment]
IMHO yes. But I'm not a maintainer of the cookbook.

**Comment by cheeseplus** [comment]
This definitely would probably be best off in it's own cookbook that might depend on the this one. At least for starters as it is highly specific. If it solves something general for a bulk of jenkins users then we could move it into core but at this point getting core _working_ is the biggest hurdle so we're trying to avoid any feature creep until we've stabilized.

**Comment by StephenKing** [comment]
so please close this. thanks

**Pull request closed without merging**
