### PR TITLE
Fix execution of jenkins commands when authorization is not enabled yet

### PR DESCRIPTION
**Pull request by dshvedchenko**
Signed-off-by: Denis Shvedchenko <dshvedchenko@sphereinc.com>

### Description

It allows fallback to anonymous auth on Jenkins LTS 2.46.2 and later

### Issues Resolved

It partially solve issue 599
and solves https://github.com/chef-cookbooks/jenkins/issues/609

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by dshvedchenko** [comment]
@iennae 
Please, if possible, review it.

**Comment by iennae** [comment]
Thanks for your contribution here!

**Comment by dshvedchenko** [comment]
maybe we need need release tag 5.0.2 ?

**Comment by iennae** [comment]
I haven't released this yet. I'm digging into the long issue that has been contributed to by a number of folks to make sure that this is actually all that needs to get updated for the next patch release. I'll be releasing it later today. Thanks!

**Pull request merged**
